test_suites:
- name: lint
  job_name: lint
  script_path: /root/okta/okta-idx-js/scripts
  sort_order: '1'
  timeout: '25'
  script_name: lint
  criteria: MERGE
  queue_name: small
- name: unit
  job_name: unit
  script_path: /root/okta/okta-idx-js/scripts
  sort_order: '2'
  timeout: '35'
  script_name: unit
  criteria: MERGE
  queue_name: ci-queue-productionJenga-Selenium-Small
- name: publish
  job_name: publish
  script_path: /root/okta/okta-idx-js/scripts
  sort_order: '3'
  timeout: '30'
  script_name: publish
  criteria: MERGE
  queue_name: small
